controllers:
    resource: ../../src/Controller/
    type: annotation
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
#
#kernel:
#    resource: ../../src/Kernel.php
#    type: annotation
